### ISSUE TITLE
Hourly Forecasts

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#1]
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

**Comment by Aniket762** [comment]
On it 🚀

**Comment by Dhruv-Sachdev1313** [comment]
I would also love to work on this one!!

**Comment by harshsharma6401** [comment]
Hey! Would love to join you on this issue.

**Comment by Aniket762** [comment]
Hey, @Dhruv-Sachdev1313 @harshsharma6401 , cool let's work on this together. I am creating a branch and setting up the basic logic to get the forecast, I actually suck at CSS so would be great if you folks can work on making it look awesome and even optimize my js. Let me know if that works for you 😁

**Comment by harshsharma6401** [comment]
> Hey, @Dhruv-Sachdev1313 @harshsharma6401 , cool let's work on this together. I am creating a branch and setting up the basic logic to get the forecast, I actually suck at CSS so would be great if you folks can work on making it look awesome and even optimize my js. Let me know if that works for you 😁

Yeah sure !

**Comment by Dhruv-Sachdev1313** [comment]
> Hey, @Dhruv-Sachdev1313 @harshsharma6401 , cool let's work on this together. I am creating a branch and setting up the basic logic to get the forecast, I actually suck at CSS so would be great if you folks can work on making it look awesome and even optimize my js. Let me know if that works for you 😁

Hey @Aniket762, That absolutely works, let me know what branch you are working on!

**Comment by Aniket762** [comment]
Hey @Dhruv-Sachdev1313 @harshsharma6401, I have worked on the issue and was able to do an hourly forecast for the next 4 hours. The particular issue is to allow users to pass time and date as param but the free version of Openweather API does not support that, I request you guys to give it a check as well. 

I have used another API to get latitude and longitude because the hourly forecast is not available in the free version of the current API so I used One call API of Openweather which takes latitude and longitude as parameters which I fetched from another API [`Opencage API`](https://opencagedata.com/) I have added the env variable name in .example.env which you need to add in your corresponding .env files. 

It is functional from my end, as I have said before the particular functionality is not present which was asked for. In case you can implement it would be really great. If not please help me with the styling and bug fixes if you encounter them.


 have given both of you access to the forked repo and you can find all the code for this issue in the `issue-1 branch` of my repo. Let's finish the work and finally send the PR together. If you face any problem let me know would be more than happy to work on it together. I

**Comment by harshsharma6401** [comment]
> Hey @Dhruv-Sachdev1313 @harshsharma6401, I have worked on the issue and was able to do an hourly forecast for the next 4 hours. The particular issue is to allow users to pass time and date as param but the free version of Openweather API does not support that, I request you guys to give it a check as well.
> 
> I have used another API to get latitude and longitude because the hourly forecast is not available in the free version of the current API so I used One call API of Openweather which takes latitude and longitude as parameters which I fetched from another API [`Opencage API`](https://opencagedata.com/) I have added the env variable name in .example.env which you need to add in your corresponding .env files.
> 
> It is functional from my end, as I have said before the particular functionality is not present which was asked for. In case you can implement it would be really great. If not please help me with the styling and bug fixes if you encounter them.
> 
> have given both of you access to the forked repo and you can find all the code for this issue in the `issue-1 branch` of my repo. Let's finish the work and finally send the PR together. If you face any problem let me know would be more than happy to work on it together. I

Cool! Will check this and get back to you.

**Comment by Dhruv-Sachdev1313** [comment]
@Aniket762 Instead of using` opencage API`, we can call `open weather` twice, once with city name, which gives us the result of latitude and longituge and then use that to call open weather again with lat and lon as parameters? What do you think ?

**Comment by Dhruv-Sachdev1313** [comment]
@Aniket762 @harshsharma6401 I have changed the open cage API to open weather current API to get latitudes and longitudes for the city. I did test it and it works😀. This way we would not need another API key and would probably not break the prod!! I am pushing my changes to `issue-1` branch in Aniket's forked repo! Do let me know if you have questions or concerns. We can improve it together!

**Comment by harshsharma6401** [comment]
> @Aniket762 @harshsharma6401 I have changed the open cage API to open weather current API to get latitudes and longitudes for the city. I did test it and it works😀. This way we would not need another API key and would probably not break the prod!! I am pushing my changes to `issue-1` branch in Aniket's forked repo! Do let me know if you have questions or concerns. We can improve it together!

Amazing ! You are a one fast dev. Having a look at it, and planning to pop questions.😁😂

**Comment by Dhruv-Sachdev1313** [comment]
@Aniket762 @harshsharma6401, Do we need to still add a feature to put time and date which would give us a result. As I feel we could only get the next 7 days' data from the free version of the API and I think the issue - Forecast the weather for the upcoming week #16 by @VaibhaveS is handling that. 
Else I feel we need to discuss this feature.

**Comment by harshsharma6401** [comment]
I don't think we need to forecast for the upcoming week since it's already an issue. But I do think we should talk about this issue.
@Aniket762 and @Dhruv-Sachdev1313 let's meet!

**Comment by Aniket762** [comment]
> I don't think we need to forecast for the upcoming week since it's already an issue. But I do think we should talk about this issue. @Aniket762 and @Dhruv-Sachdev1313 let's meet!

The issue states to give the weather report for any time and date are given, I guess we should also tackle this edge case. If you guys think we shouldn't then you may remove the functionality 🙂

**Comment by harshsharma6401** [comment]
> > I don't think we need to forecast for the upcoming week since it's already an issue. But I do think we should talk about this issue. @Aniket762 and @Dhruv-Sachdev1313 let's meet!
> 
> The issue states to give the weather report for any time and date are given, I guess we should also tackle this edge case. If you guys think we shouldn't then you may remove the functionality 🙂

If it's already there, then there is no need to change it!
