### ISSUE TITLE
Setup ESLint and Prettier

### ISSUE THREAD

**Issue by CIPHERTron** [MLH-Fellowship/prep-project-jan-2022#10]
**ESLint** for code linting and managing errors & **Prettier** for code formatting.
Just to maintain a uniform coding standards :)

References: 
ESLint: https://eslint.org/
Prettier: https://prettier.io/

**Comment by KshitijDarekar** [comment]
Interested

**Comment by ditsuke** [comment]
@KshitijDarekar lets team up!

**Comment by yyjlincoln** [comment]
Probably also add an `.eslintrc` along with `.editorconfig` (#8) to enforce consistent code style/practices? I think airbnb's standards are quite good & I believe they are widely used.
https://github.com/airbnb/javascript

**Comment by CIPHERTron** [comment]
> Probably also add an `.eslintrc` along with `.editorconfig` (#8) to enforce consistent code style/practices? I think airbnb's standards are quite good & I believe they are widely used. https://www.npmjs.com/package/eslint-config-airbnb https://github.com/airbnb/javascript

Yeah, Airbnb has one of the best standards out there. We can extend to it in the `.eslintrc`. But for `.editorconfig`, I don't think we'll require it if we use Prettier or vice-versa.

Refs:
https://dev.to/knowankit/setup-eslint-and-prettier-in-react-app-357b

**Comment by KshitijDarekar** [comment]
Airbnb Config is a popular choice, I think we can go with it. Just to mention the other alternatives could be to use `eslint:recommended` or the standard config.
Refs:
https://eslint.org/docs/rules/
https://github.com/standard/eslint-config-standard

**Comment by ditsuke** [comment]
Let's go with the airbnb base

**Comment by KshitijDarekar** [comment]
We can also add Husky and lint-stage with the prettier and eslint config. Basically includes commit hooks which will run whenever we make commits.
Ref:
https://medium.com/gits-apps-insight/utilizing-git-hook-by-using-eslint-husky-and-lint-staged-18b6f6f60f1e

**Comment by ditsuke** [comment]
> We can also add Husky and lint-stage with the prettier and eslint config. Basically includes commit hooks which will run whenever we make commits. Ref: [medium.com/gits-apps-insight/utilizing-git-hook-by-using-eslint-husky-and-lint-staged-18b6f6f60f1e](https://medium.com/gits-apps-insight/utilizing-git-hook-by-using-eslint-husky-and-lint-staged-18b6f6f60f1e)

I like this idea, a lot. We should include the Husky config in the PR for this issue!
