### ISSUE TITLE
Use TailwindCSS

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/prep-project-jan-2022#12]
Use TailwindCSS instead of writing normal CSS code as it's easier to maintain & easy to:
- Implement adaptive styles (works on mobile & laptop etc through `sm:`, `md:`, `lg:` etc)
- Implement dark mode (using `dark:`)

Stay in the same HTML file instead of constantly switching to CSS files

https://tailwindcss.com/

**Comment by yyjlincoln** [comment]
I will be interested

**Comment by CIPHERTron** [comment]
Or we can use Styled Components?

ps: not a big fan of Tailwind CSS :')

**Comment by yyjlincoln** [comment]
ah... interesting. I'm not too sure whether we can implement above features easily in Styled Components though

**Comment by yyjlincoln** [comment]
We can probably do both?

**Comment by Aniket762** [comment]
> Or we can use Styled Components?
> 
> ps: not a big fan of Tailwind CSS :')

Yes styled-components or emotion would be easier for me to implement as well 🙈

**Comment by Chukwuemeka-Mba** [comment]
Interested

**Comment by CIPHERTron** [comment]
> We can probably do both?

Yes. Definitely, we can. 
But let's ask what the rest of the pod members first think about this since we all will be working together on this project :D

**Comment by ditsuke** [comment]
I don't have any experience with Tailwind or any of the other tools mentioned here, styled components look interesting but I leave it open! Maybe we can go with @yyjlincoln's suggestion though and use both but I'm not sure how well they play together 🙌

**Comment by harshsharma6401** [comment]
Like @ditsuke, I don't have any experience with either of the things mentioned. Let's try both and see what suits us best.😃

**Comment by CIPHERTron** [comment]
> Maybe we can go with @yyjlincoln's suggestion though and use both but I'm not sure how well they play together 🙌

@ditsuke They don't actually play together. If we use both, it'll be essentially like using two frameworks or two different ways of styling (separately).

I usually prefer css-in-js while writing CSS in React or other JS frameworks. We can also use Tailwind with Styled Components but for that, we've to use another library called [twin.macro](https://www.npmjs.com/package/twin.macro) which gives us the functionality to leverage the use of Tailwind in Styled Components.

**Comment by yyjlincoln** [comment]
Yeah I'm not too sure how well they play together either. `Tailwind` is **css in html** (using classes)
- For example, if I want to apply: ```display: flex; flex-direction: row``` for a specific element `<div></div>`:
```<div className="flex flex-row"></div>```
- Or if I want to also add a `@media` tag so that it becomes `flex-direction: column` on mobile:
```<div className="flex flex-column md:flex-row"></div>```  (only when screen size > md (medium) then we'll use flex-row
- Dark mode is easy with `dark:` in front of any class - they will only be activated in dark mode.
```<div className="bg-white dark:bg-black"></div>```
- You can use it to create components as well - Just use {children}, for example:
```
function testComponent({children, param, ...args}){ // ...args here passes on everything else to the outer div such as onClick
    return (
        <div className="flex flex-row" {...args}>
            {children}
        </div>
    )
}

Then,
function App() {
    return (
        // Other divs
        <testComponent param={true} onClick={()=>{console.log('hello')}}>
            // Children
        </testComponent>
    )
}
```

*Note that in JSX syntax, we'll need to use `className` instead of `class`

I haven't worked with StyledComponent/Emotion for too long so I can't say much about StyledComponent/Emotion. I think it's like css-in-js but I will be open to using them as well! I just personally prefer Tailwind as I prefer using css in html rather than css in js

**Comment by gmelodie** [comment]
Not sure having two technologies do the same task is a good idea. Also learning two different techs might be a bit too much. Let's settle on one!

**Comment by ditsuke** [comment]
@MLH-Fellowship/mlh-prep-january-2022 let's decide on something today! If we want to go with Styled Component there's still a way to nominally include tailwind the CSS-in-JS way with [twin.macro](https://www.npmjs.com/package/twin.macro). However it looks like most current PRs are using Vanilla CSS, so we need to make the addition ASAP to have any time to work with it.

**Comment by psahithireddy** [comment]
I would slide with Emotion/styledcomponents when ccompared with tailwind CSS.But i think MUI(material UI) is lot simpler than both of them. Take a look here, https://mui.com/components/buttons/

**Comment by ditsuke** [comment]
@MLH-Fellowship/mlh-prep-january-2022 I've posted a poll link on the discord. Lets get to a decision and close this issue.

**Comment by gmelodie** [comment]
According to vote done today, we're using Material UI instead.
