### ISSUE TITLE
Implement weather warnings 

### ISSUE THREAD

**Issue by Chukwuemeka-Mba** [MLH-Fellowship/prep-project-jan-2022#13]
A red banner that notifies the user of extreme weather conditions. 

E.g. 
- Typhoons
- Extreme rain
- Snow
- Heat
- Tornado

**Comment by KhudaDad414** [comment]
Interested!

**Comment by harshsharma6401** [comment]
I am also interested, lets team up!

**Comment by ditsuke** [comment]
Interested as well!
