### ISSUE TITLE
Add Github Actions for Unit Testing and Linting

### ISSUE THREAD

**Issue by ditsuke** [MLH-Fellowship/prep-project-jan-2022#18]
We should have unit tests and linting run on all commits and PRs. Github Actions are convenient for this.

**Comment by ditsuke** [comment]
I'd like to work on this once PR #17 is merged! 😄

**Comment by psahithireddy** [comment]
I would like to work on this.

**Comment by gmelodie** [comment]
Great idea! This is not a core feature but it's a great learning opportunity! I'm all for it :)

**Comment by KshitijDarekar** [comment]
We would not need Husky,lint-staged if implemented this or vice-versa, I guess.
