### ISSUE TITLE
Change the colour scheme based on temperature / weather type

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#2]
Change the websites appearance to match the weather conditions. The Apple Weather app has some cool examples in iOS 15, check them out [here](https://9to5mac.com/2021/09/24/ios-15-weather-app-hands-on/).

**Comment by anubhav06** [comment]
I'd like to work on this !

**Comment by Riyadevvarshney11** [comment]
I would like to work on this as well

**Comment by harshsharma6401** [comment]
I would love to join you guys with this issue.
