### ISSUE TITLE
Add PWA support to the react application

### ISSUE THREAD

**Issue by CIPHERTron** [MLH-Fellowship/prep-project-jan-2022#21]
**_Progressive Web Apps (PWAs) are web apps that use service workers, manifests, and other web-platform features in combination with progressive enhancement to give users an experience on par with native apps._**

I think this will be a great enhancement to our application.

Reference: https://web.dev/progressive-web-apps/
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

**Comment by CIPHERTron** [comment]
I can work on this feature 💯

**Comment by CIPHERTron** [comment]
I can work on it.

@gmelodie your views on this?

**Comment by harshsharma6401** [comment]
I would love to join you on this issue. It seems like a great opportunity!

**Comment by KshitijDarekar** [comment]
I would like to work on this with both of you as well @CIPHERTron @harshsharma6401

**Comment by ditsuke** [comment]
I'd love to jump in if there's any room! 😂

**Comment by CIPHERTron** [comment]
OMG we have so many folks interested to work on this haha
Let me open a PR with the basic service worker setup. Then, maybe we can work on that i.e. the manifests, favicons and stuff.

Does that sound good @ditsuke @KshitijDarekar @harshsharma6401?
