### ISSUE TITLE
Using Geolocation API to get the users location

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#3]
Using the Geolocation API to get the users location as the first weather results displayed, instead of just New York City.

Read more [here](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API).

**Comment by KhudaDad414** [comment]
Interested!

**Comment by yyjlincoln** [comment]
Interested

**Comment by VaibhaveS** [comment]
Interested!
