### ISSUE TITLE
reduce the api calls w.r.t the onChange event handler (debouncing)

### ISSUE THREAD

**Issue by CIPHERTron** [MLH-Fellowship/prep-project-jan-2022#39]
As of now, the OpenWeather API call is triggered every time the onChange event handler is called which is not required IMO. We can reduce the number of API calls by debouncing the function such that after each 1sec or 500ms only the OpenWeather API is called.

Reference: https://medium.com/@markotroskot/debouncing-and-throttling-in-react-feb84d84bf28

**Comment by CIPHERTron** [comment]
@MLH-Fellowship/mlh-prep-january-2022 need your views on this. If the majority agree, I can start working on this 🚀

**Comment by Chukwuemeka-Mba** [comment]
What about the one call API Tushar suggested?

**Comment by ditsuke** [comment]
> As of now, the OpenWeather API call is triggered every time the onChange event handler is called which is not required IMO. We can reduce the number of API calls by debouncing the function such that after each 1sec or 500ms only the OpenWeather API is called.
> 
> Reference: [medium.com/@markotroskot/debouncing-and-throttling-in-react-feb84d84bf28](https://medium.com/@markotroskot/debouncing-and-throttling-in-react-feb84d84bf28)

@CIPHERTron 
This is a great suggestion! However as we added of the search suggestions we also [changed the `setCity()` trigger from `onChange` to `onSelect`](https://github.com/MLH-Fellowship/prep-project-jan-2022/pull/20/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67L37), so in my opinion this is not a concern anymore as we're only calling the API once a suggestion is selected.

**Comment by CIPHERTron** [comment]
Oh, I see. It's already changed haha
We don't require it anymore. Thus, closing this issue.
