### ISSUE TITLE
Make the Target symbol for fetching location

### ISSUE THREAD

**Issue by harshsharma6401** [MLH-Fellowship/prep-project-jan-2022#47]
###    Improve UX with location
- By default, the website shows the weather of our location, which is fine.
- After surfing the website, when we want to check the weather of our location once again, We have to either search it, pinpoint it or reload the website. It is not the appropriate and convenient way.
- In these situations, the symbol shown below comes handy. It is present in almost every website dealing with the location; we should include it. 

![Location Symbol](https://user-images.githubusercontent.com/71374972/150934528-fd5a3426-fdaf-4a87-85c5-a830080b80f6.jpg)

**Comment by Chukwuemeka-Mba** [comment]
Aye aye sir!
