### ISSUE TITLE
String Injection - User input is not parsed or escaped (Security)

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/prep-project-jan-2022#49]
This works kinda like a SQL injection - but with the request API. It's not a major security issue (as it's unlikely to cause any issues at least for this use case) but this kind of behaviour should be fixed regardless to improve the security of the application.

Currently, we're using the template syntax (`https://..../q=${var}`) to compose the requested URL. This is unsafe as a malicious user can craft a string (that contains special characters such as `&`) to cause unexpected behaviours.

For example, if a `redirect` param is provided, an XSS attack may be possible. (The user's browser is tricked to access a certain URL)

Please check the screenshots:

<img width="1532" alt="Screen Shot 2022-01-25 at 10 16 51 pm" src="https://user-images.githubusercontent.com/20881008/150967281-0b7c6453-75f3-4aae-a061-e1e48fe88583.png">
<img width="1119" alt="Screen Shot 2022-01-25 at 10 17 11 pm" src="https://user-images.githubusercontent.com/20881008/150967326-577141d4-e9b0-465d-ab51-9205a725d0d9.png">

The user's input should be either parsed or escaped to avoid issues. Alternatively, libraries such as `axios` can be used which would handle this automatically (instead of `fetch`).

Never trust the inputs from your users :)

**Comment by anubhav06** [comment]
If it's really an issue then I would like to work on this. Although I think it shouldn't be as we are just making a GET request to get the weather data 🤔
