### ISSUE TITLE
Map for selecting location

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#5]
Instead of just typing the location in, display a map to the user (using OpenStreetMap for example), and take the coordinates of their pin and use that to display weather information.

Make it a 2 way thing, and if a user types a location in, it displays a pin on the map as well!

If you have an API key, let @wrussell1999 know so it can be added to the Netlify website hosting it!

**Comment by CIPHERTron** [comment]
Would love to work on this issue 🚀

**Comment by harshsharma6401** [comment]
Interested

**Comment by KshitijDarekar** [comment]
Would like to work on this as well
