### ISSUE TITLE
Autocomplete for cities

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#6]
At the moment, when you type in a city, it won't help you finish your entry with suggestions. A cool feature would be if it had a drop down menu that suggested locations similar to the name. For example, if I type in `Cambridge`, it could tell me `Cambridge, MA, USA` or `Cambridge, UK` to help users get the right answers!

**Comment by adizcode** [comment]
Interested!

**Comment by yyjlincoln** [comment]
Interested

**Comment by ditsuke** [comment]
Interested as well!
