### ISSUE TITLE
Improve mobile usability

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-jan-2022#7]
The card that displays the weather information isn't responsive. It's far too narrow on mobile, and too wide on desktop. Can you look into making it be an appropriate size on all screen sizes.

**Comment by psahithireddy** [comment]
would like to work on this.

**Comment by CIPHERTron** [comment]
Didn't see this issue haha
I can help with it since I had assigned only 1 issue to myself(which is almost complete)
